name: Publish Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v1.0.1

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'thesysdev/create-c1-app'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Set node version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
